mobile={brand:"Apple", model:"iPhone 12", os:"iOS 14"};
console.log(mobile);
console.log(mobile.brand);
mobile.model="iPhone 13";
console.log(mobile.model);
delete mobile.os;
console.log(mobile);
newMobile=Object.assign(mobile);
console.log(newMobile); 
let keys=Object.keys(mobile);
console.log(keys);
let values=Object.values(mobile);
console.log(values);
let entries=Object.entries(mobile); 
console.log(entries);
let has=mobile.hasOwnProperty("brand");
console.log(has);   
